### ISSUE TITLE
Update frontend to better integrate secret-to-token behaviour

### ISSUE THREAD

**Issue by ddamico** [nielsmaerten/gluco-check#122]
** update react-hook-form either before this or as part of it, looks like there are changes in there that relate specifically to some of the behaviour changes we want to do https://react-hook-form.com/migrate-v6-to-v7/ **

Per conversation on Apr. 17th, the plan here is to...
* validate input on submission instead of on change
* switch the form label to token or api secret
* add some copy explaining that we’re not going to retain secret, but will use it to generate token
* update the field value to the "cleaned" value returned from the validation endpoint

**Comment by ddamico** [comment]
@nielsmaerten in your opinion, should we save the user's input even if validation returns warnings? (ie if url or token are invalid, should we warn and not save, or warn but still save?)

**Comment by nielsmaerten** [comment]
@ddamico IMHO, yes. The user clicks "Save settings", so that's what we should do.  
We'll show a warning when the credentials entered aren't working, but they're saved nonetheless.

I think you can take some inspiration from [Nightscout Status](https://git.io/nightscoutstatus). Its flow is basically as follows:

- While user is typing their url/token: 
  Regex validation happens on-the-fly. The field gets marked with a warning if the value is not a valid url
- After user clicks "Save":
  A dialog with the title "Settings saved" appears, inside it is a spinner indicating we're busy validating the url/token combo.
  - If validation passes, we show a success message and possible next actions (*)
  - If validation fails, we show a warning message and tips to remedy the error

(*) Possible next actions could be:
* Prompting the user to try to invoke Gluco Check on their device
* How to set up a Routine to shorten your invocation (eg Hey Google, check my sugar)

**Comment by ddamico** [comment]
@nielsmaerten what's your take on what the regex for a token would be? an actual token seems predictable enough, [whatever]-[17 characters], but a secret could be anything right? Am I answering the question right there? Would the behaviour be "if it's the token form use that expression, if it has a value but doesn't match the token expression then assume the user is providing a secret"?  Or am I possibly misremembering and the form of the secret is predictable? It's been so long since I set it up (probably a hint that I should consider rotating it haha).

**Comment by nielsmaerten** [comment]
@ddamico I don't think it will be possible to do offline/regex validation on that field. You're right an API secret can be anything. And even tokens don't have to follow the `[whatever]-[hex number]` structure. Nightscout only checks if the token endsWith the hex number. So for a token `glucocheck-abc123` these would all be valid:
* glucocheck-**abc123**
* **abc123**
* foobar-**abc123**
* loremipsumdolorsit.com/ametconsequetur.html/waitIsThisEvenAUrl?!#£%😵aaaaaaa**abc123**

My take would be: don't show any feedback on the validity of what's in the token/secret field until after it's been validated on the server.
