### ISSUE TITLE
Voice not recognized 

### ISSUE THREAD

**Issue by wsangster** [nielsmaerten/gluco-check#162]
I have the glucocheck set up for my Goggle Assistant for my son's Nightscout site. I also set it up on his Google Assistant. During the initial tests it seems to work, but now when we ask for results  it comes back and says it doesn't recognize us. I can ask Google who I am right before I ask about the blood sugar. It will respond with my name, but then won't give me the BG level. 
Sometimes it will work and when it does it's great. 
I even set up a Routine to make it easier to say so Google should get less confused about any pronunciation. 
Ideally if I could have it just say the number regardless of who asks that would the best case for us. 
Thanks

**Comment by nielsmaerten** [comment]
Hey @wsangster 

When you say it's not recognizing you, do you mean:
* Google says: "Your voice wasn't recognized, so I can't tell you your BG right now"
* Or: does Assistant misunderstand the words 'Gluco Check' and thinks you're asking for something else?

In the first case, [retraining the voice model](https://www.howtogeek.com/338071/how-to-retrain-your-google-assistant-voice-model/) for you and your son could help.
In the second case... Yeah, `¯\_(ツ)_/¯`  there's not much we can do.

That's just Google's Voice AI being finicky. It gets better over time. 
When it gets it wrong, follow up with: "Hey Google, that's not what I said" or "Hey Google, _I said_: Talk to Gluco Check". 
The more people use Gluco Check, the better Assistant gets at recognizing the name.

You mentioned you were already using Routines. I think that's indeed the best workaround if this issue keeps bugging you.

**Comment by wsangster** [comment]
Sorry for the delayed reply. It's the first case. I have tried retraining
my voice a few times. The routine won't even let it go through. Which is
odd because I'm the only one with that routine set up. So google knows that
it's me and to fire off my routine but then Gluco Check replies back
something very similar to what you wrote. Although not that exact phrasing.
When I get home I'll check the exact words and let you know.

**Comment by nielsmaerten** [comment]
Ok, if it's the first case you can pretty much ignore the second half of my previous message.

But when it says "Since your voice wasn't recognized, bla bla bla..." turns out that's actually Google talking, not Gluco Check. 

When Gluco Check gets a question from someone it doesn't recognize, it will ask them to visit the website and link their Nightscout.

When Google doesn't recognize you, it says the phrase you're hearing.

The reason for this is that when Google calls on Gluco Check, it must be able to share which account asked the question. Otherwise Gluco Check can't know whose Nightscout to check. There's hundreds of sites in our database, and we don't want to accidentally read out someone else's information. So this voice check is pretty strict.

Did you retrain Voice Match for all members in your household? It's a long shot, but maybe it's confusing you with someone else.

Finally... And I'm sorry if this sounds a little insensitive, but is English your native language?
My own native language is Dutch, and I've noticed that (very occasionally) the system has trouble recognizing my accent. Then I take on a more Americanized accent, and suddenly it works 😉
